db:
  username: username
  password: password
  url: ../dev.db
server:
  address: 127.0.0.1
  port: 8080
client:
  origin: "*"
  #origin: http://localhost:3000/
security:
  rsaKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEA1mfLUPfn5/0fBaVieqoC+9K0eJ0ZTP3cAk8q5tdqgzwNWSofj//g
    Uexqxm1QFPANwtpfpaP5k/x2yYMDGPaK1lqhYluE75nCqEibPVD58BD7WsESvqsr8vbXBS
    0FQnv1Hg0KwfFhNcNKQYyFPs5iYHZriOxvMvwHNoocUtmv44y8qGOtK+CMdpt7xIHjXWfE
    qT9uIckv5AVg7TAnY1OWCwf2U3f65bU7Y54w59U7p9JrY2E/ylhY4ngSIf2mko03fH0dfV
    duiCoZrdWC055/QjqbSXy0uZY5l4kPNkyY15wwhatBQExRPlb0bopcTK8JcC/GjmMHulZY
    K+XpPpV7x/n1FmHJXu8XUqF4CSx0WCYEIV7oTRF5B0efsyvnuaESuGq+gg9Gxt0UlWXAiC
    n3XQJUJsthANEjH4OJudytkkbw1N/fSQi3BKXUewEXYafxbrS7ZIJTzzCXsNF9l+s+XLi2
    /bgh37EyT9pbc5EMXuWQFDKTmtlp63f/b72paMhfAAAFoN327AXd9uwFAAAAB3NzaC1yc2
    EAAAGBANZny1D35+f9HwWlYnqqAvvStHidGUz93AJPKubXaoM8DVkqH4//4FHsasZtUBTw
    DcLaX6Wj+ZP8dsmDAxj2itZaoWJbhO+ZwqhImz1Q+fAQ+1rBEr6rK/L21wUtBUJ79R4NCs
    HxYTXDSkGMhT7OYmB2a4jsbzL8BzaKHFLZr+OMvKhjrSvgjHabe8SB411nxKk/biHJL+QF
    YO0wJ2NTlgsH9lN3+uW1O2OeMOfVO6fSa2NhP8pYWOJ4EiH9ppKNN3x9HX1XbogqGa3Vgt
    Oef0I6m0l8tLmWOZeJDzZMmNecMIWrQUBMUT5W9G6KXEyvCXAvxo5jB7pWWCvl6T6Ve8f5
    9RZhyV7vF1KheAksdFgmBCFe6E0ReQdHn7Mr57mhErhqvoIPRsbdFJVlwIgp910CVCbLYQ
    DRIx+DibncrZJG8NTf30kItwSl1HsBF2Gn8W60u2SCU88wl7DRfZfrPly4tv24Id+xMk/a
    W3ORDF7lkBQyk5rZaet3/2+9qWjIXwAAAAMBAAEAAAGAF2/pLcSruRRWW8ukZDxJbzWtPL
    IPnfbyId59lhZeMlJSMzkDkj4qS0pIscApTOCg4Hf2lKjEE4U5hvWnVQc+TghCM/pFIdvx
    B2xIa/96EuAIWfdZETas6zZIcuxk8suSE+LhFipIshPS/i9aMW9mGZ1YS/NshGpAb5nRVs
    0tCPbNeKrMt0soj56XfPel3wQE32troo3Xill8KvFknNr6P+Jy7tTivFF/WHhmaDFLACFk
    U8zBqGDX9omhkc2kc8iz4MR+VYmsr6kpRtyCLv15+urVGq9XhOpfOTJ+q9C4upBYIvkzgE
    zuh3jHjY2XddBOpstIlcC9IhbxPvAHFxsh7oOzK5vYzNaoItxpie/BbYSkDqgYQdBoh7vF
    zIpVafyzGTBWQsk4E3A730XcT5kZMlghCDdWShqrwy9+nPfGP2DVJMPzrWc23wwkybraaW
    fMpIzBXSMeMnI1QQXaolcPwfDfNBk3MVh6ID/7zvnabvGsqDP4Qz6ZW11ZCII2FP5hAAAA
    wGPxco85qftSV1vhi6yJwZ8r2q+IgIBCNHVrQyV2WehxoqsUw6LDOth/WNaXUO3HkaPevo
    TebjkuzBitgFTCeXEx2bo+YWXLc8nWoB+8GfWOMVgJsFQZZEU1gvzQIsB/vVWVeZkSla/j
    R+pfxxasvtKN6ip8djE8hbVn4hcOVStqtEMDrHvV86cBwgI+COgTre1JEUlXMKJEKB9VFT
    ea5AkIptA6R8gJ4e+hftUM1D7pBa2aObKQFIu1Hc7NM9DLPQAAAMEA9bsQmftrjEMJ0dY5
    W90Hk1zdACZ2+8ntcJuv9MVmmINBePNPt508Gz1aSu7jTj0fCFSV4mI+jcVvy+rta0ySd5
    V+Az4lApMqSyl6rLAq+LX5LtrujShkzDaEKwaeHnncAoJ8OrblweZANe3cQY87wSwIwuvC
    OtuzjR7MRn3v+Dc9tQq+tE+tzrZMaUtePpptt/HdyeV/2GPrl9EzR3pC2GCMpSZy8eHmdB
    G62bhCCHrVsLs/ak1MAAWnQjylIHZDAAAAwQDfXZkJYV0hJKJeb0/q+ZtnOcs9UHHnd9EZ
    SW2cK/urjFSPLBARmhzXXj8l2ni6s4HO2DXsa5l5mzkRLTma42Ob8qCNGXqZRQVqyk6bwq
    JggdqETkUm8bbjSvE2GFp2Dpb7iaeCZZHhXKATXS1oSYQrTGH2Okus6ROY2it+3NbJ+mIq
    Ok+PC4AyQSeFEqCK44+QsKTu7Zxy2rDXkWItgQ802VboWT+h7AunZLZdUzyomg3whb+0zf
    1CiqEm9LP6+bUAAAAncy1kb2JyaWpldmljQHMtZG9icmlqZXZpYy1MYXRpdHVkZS01NTAx
    AQIDBA==
    -----END OPENSSH PRIVATE KEY-----
