// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Airports string
	Cities   string
	Comments string
	Routes   string
	Users    string
}{
	Airports: "airports",
	Cities:   "cities",
	Comments: "comments",
	Routes:   "routes",
	Users:    "users",
}
