// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRoutes(t *testing.T) {
	t.Parallel()

	query := Routes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRoutesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoutesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Routes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoutesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RouteSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoutesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RouteExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Route exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RouteExists to return true, but got false.")
	}
}

func testRoutesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	routeFound, err := FindRoute(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if routeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRoutesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Routes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRoutesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Routes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRoutesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	routeOne := &Route{}
	routeTwo := &Route{}
	if err = randomize.Struct(seed, routeOne, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}
	if err = randomize.Struct(seed, routeTwo, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = routeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = routeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Routes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRoutesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	routeOne := &Route{}
	routeTwo := &Route{}
	if err = randomize.Struct(seed, routeOne, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}
	if err = randomize.Struct(seed, routeTwo, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = routeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = routeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func routeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func routeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Route) error {
	*o = Route{}
	return nil
}

func testRoutesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Route{}
	o := &Route{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, routeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Route object: %s", err)
	}

	AddRouteHook(boil.BeforeInsertHook, routeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	routeBeforeInsertHooks = []RouteHook{}

	AddRouteHook(boil.AfterInsertHook, routeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	routeAfterInsertHooks = []RouteHook{}

	AddRouteHook(boil.AfterSelectHook, routeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	routeAfterSelectHooks = []RouteHook{}

	AddRouteHook(boil.BeforeUpdateHook, routeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	routeBeforeUpdateHooks = []RouteHook{}

	AddRouteHook(boil.AfterUpdateHook, routeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	routeAfterUpdateHooks = []RouteHook{}

	AddRouteHook(boil.BeforeDeleteHook, routeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	routeBeforeDeleteHooks = []RouteHook{}

	AddRouteHook(boil.AfterDeleteHook, routeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	routeAfterDeleteHooks = []RouteHook{}

	AddRouteHook(boil.BeforeUpsertHook, routeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	routeBeforeUpsertHooks = []RouteHook{}

	AddRouteHook(boil.AfterUpsertHook, routeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	routeAfterUpsertHooks = []RouteHook{}
}

func testRoutesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRoutesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(routeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRouteToOneAirportUsingDestination(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Route
	var foreign Airport

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, airportDBTypes, false, airportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Airport struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DestinationID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Destination().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RouteSlice{&local}
	if err = local.L.LoadDestination(ctx, tx, false, (*[]*Route)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Destination == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Destination = nil
	if err = local.L.LoadDestination(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Destination == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRouteToOneAirportUsingSource(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Route
	var foreign Airport

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, routeDBTypes, false, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, airportDBTypes, false, airportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Airport struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.SourceID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Source().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RouteSlice{&local}
	if err = local.L.LoadSource(ctx, tx, false, (*[]*Route)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Source == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Source = nil
	if err = local.L.LoadSource(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Source == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRouteToOneSetOpAirportUsingDestination(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Route
	var b, c Airport

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, routeDBTypes, false, strmangle.SetComplement(routePrimaryKeyColumns, routeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, airportDBTypes, false, strmangle.SetComplement(airportPrimaryKeyColumns, airportColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, airportDBTypes, false, strmangle.SetComplement(airportPrimaryKeyColumns, airportColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Airport{&b, &c} {
		err = a.SetDestination(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Destination != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DestinationRoutes[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DestinationID != x.ID {
			t.Error("foreign key was wrong value", a.DestinationID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DestinationID))
		reflect.Indirect(reflect.ValueOf(&a.DestinationID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DestinationID != x.ID {
			t.Error("foreign key was wrong value", a.DestinationID, x.ID)
		}
	}
}
func testRouteToOneSetOpAirportUsingSource(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Route
	var b, c Airport

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, routeDBTypes, false, strmangle.SetComplement(routePrimaryKeyColumns, routeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, airportDBTypes, false, strmangle.SetComplement(airportPrimaryKeyColumns, airportColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, airportDBTypes, false, strmangle.SetComplement(airportPrimaryKeyColumns, airportColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Airport{&b, &c} {
		err = a.SetSource(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Source != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SourceRoutes[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.SourceID != x.ID {
			t.Error("foreign key was wrong value", a.SourceID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SourceID))
		reflect.Indirect(reflect.ValueOf(&a.SourceID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.SourceID != x.ID {
			t.Error("foreign key was wrong value", a.SourceID, x.ID)
		}
	}
}

func testRoutesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRoutesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RouteSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRoutesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Routes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	routeDBTypes = map[string]string{`ID`: `INTEGER`, `SourceID`: `BIGINT`, `DestinationID`: `BIGINT`, `Price`: `REAL`}
	_            = bytes.MinRead
)

func testRoutesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(routePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(routeAllColumns) == len(routePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, routeDBTypes, true, routePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRoutesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(routeAllColumns) == len(routePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Route{}
	if err = randomize.Struct(seed, o, routeDBTypes, true, routeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Routes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, routeDBTypes, true, routePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Route struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(routeAllColumns, routePrimaryKeyColumns) {
		fields = routeAllColumns
	} else {
		fields = strmangle.SetComplement(
			routeAllColumns,
			routePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RouteSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
